/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nimi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class School extends javax.swing.JFrame {

  
    public School() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        num = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        add = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        nem = new javax.swing.JTextField();
        gram = new javax.swing.JComboBox<>();
        ledge = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("DELETE");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 40));

        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        jPanel2.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 280, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 51));
        jRadioButton1.setText("Male");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 102));
        jRadioButton2.setText("Female");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, 30));
        jPanel2.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 80, 30));

        nem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemActionPerformed(evt);
            }
        });
        jPanel2.add(nem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 280, 30));

        gram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT PROGRAM", "BSCS" }));
        jPanel2.add(gram, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 140, 30));

        ledge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT COLLEGE", "CTECH", "CTE", "COM", "COF" }));
        ledge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgeActionPerformed(evt);
            }
        });
        jPanel2.add(ledge, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Age", "Gender", "Address", "Contact Number", "College", "Program"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 900, 300));

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 51));
        jButton6.setText("CLEAR");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, 40));

        jButton7.setBackground(new java.awt.Color(51, 102, 255));
        jButton7.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 51));
        jButton7.setText("UPDATE");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, 40));

        jButton8.setBackground(new java.awt.Color(51, 102, 255));
        jButton8.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 51));
        jButton8.setText("SAVE");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 40));

        jButton9.setBackground(new java.awt.Color(51, 102, 255));
        jButton9.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 51));
        jButton9.setText("SHOW");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 40));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("CONTACT NUMBER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 150, 20));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 60, 50, 20));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("AGE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 40, 20));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("ADDRESS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1035, 633));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nemActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        // Clear text fields
        nem.setText("");
        edad.setText("");
        add.setText("");
        num.setText("");

// Reset combo boxes
        ledge.setSelectedIndex(0);
        gram.setSelectedIndex(0);

// Clear radio buttons
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);

// Optional: clear JTable selection
        jTable1.clearSelection();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void ledgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgeActionPerformed

        if (ledge.getSelectedItem().equals("CTECH")) {
            gram.removeAllItems();
            gram.setSelectedItem(null);
            gram.addItem("BSCS");
            gram.addItem("BSIT-ELECT");
            gram.addItem("BSIT-FPST");
        } else if (ledge.getSelectedItem().equals("CTE")) {
            gram.removeAllItems();
            gram.addItem("BSED-ENGLISH");
            gram.addItem("BSED-MATH");
            gram.addItem("BEED");
        } else if (ledge.getSelectedItem().equals("COM")) {
            gram.removeAllItems();
            gram.addItem("BS-MIDWIFERY");
        } else if (ledge.getSelectedItem().equals("COF")) {
            gram.removeAllItems();
            gram.addItem("BS-FISHERIES");
        } else if (ledge.getSelectedItem().equals("SELECT COLLEGE")) {
            gram.removeAllItems();
        }
    }//GEN-LAST:event_ledgeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        String name = nem.getText();
        int age = Integer.parseInt(edad.getText());
        String address = add.getText();
        String contact = num.getText();  // text field input as a String
        String college = ledge.getSelectedItem().toString();
        String program = gram.getSelectedItem().toString();
        String gender = "";

        if (jRadioButton1.isSelected()) {
            gender = "Male";
        } else if (jRadioButton2.isSelected()) {
            gender = "Female";
        }

        try {
            // Load MySQL JDBC Driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to database
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydata?useSSL=false", "root", "");

            // SQL Insert
            String sql = "INSERT INTO dateta (snam, edz, genda, ress, nmber, kalids, prgram) VALUES (?, ?, ?, ?, ?, ?, ?)";
            //PreparedStatement pst = con.prepareStatement(sql);
            PreparedStatement pst = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            // Set values
            pst.setString(1, name);
            pst.setInt(2, age);
            pst.setString(3, gender);
            pst.setString(4, address);
            pst.setString(5, contact);  // Use setInt() for integer values
            pst.setString(6, college);
            pst.setString(7, program);

            // Execute
            pst.executeUpdate();

            ResultSet rs = pst.getGeneratedKeys();

            //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            //model.addRow(new Object[]{ name, age, gender, address, contact, college, program});
            // 5. Success message
            JOptionPane.showMessageDialog(null, "Data Saved Successfully!");

            // Clear fields if needed
            nem.setText("");
            edad.setText("");
            add.setText("");
            num.setText("");
            ledge.setSelectedIndex(0);
            gram.setSelectedIndex(0);
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        // Clear existing rows in JTable before displaying new data
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);  // This removes all existing rows in the JTable

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydata?useSSL=false", "root", "");

            String sql = "SELECT * FROM dateta";  // Select all data from the table
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                // Assuming your columns in JTable are: id, name, age, gender, address, contact, college, program
                Object[] row = new Object[8];
                row[0] = rs.getInt("id");  // student_id
                row[1] = rs.getString("snam");     // name
                row[2] = rs.getInt("edz");         // age
                row[3] = rs.getString("genda");    // gender
                row[4] = rs.getString("ress");     // address
                row[5] = rs.getString("nmber");    // contact
                row[6] = rs.getString("kalids");   // college
                row[7] = rs.getString("prgram");   // program

                model.addRow(row);  // Add the new row to the JTable
            }

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row to update.");
            return;
        }

        int studentId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        String name = nem.getText().trim();
        String ageText = edad.getText().trim();
        String address = add.getText().trim();
        String contact = num.getText().trim();
        String college = ledge.getSelectedItem().toString();
        String program = gram.getSelectedItem().toString();
        String gender = "";

        if (jRadioButton1.isSelected()) {
            gender = "Male";
        } else if (jRadioButton2.isSelected()) {
            gender = "Female";
        }

// Parse age (set to 0 if empty or invalid)
        int age = 0;
        try {
            age = Integer.parseInt(ageText);
        } catch (NumberFormatException e) {
            // leave age as 0
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydata?useSSL=false", "root", "");

            String sql = "UPDATE dateta SET snam=?, edz=?, genda=?, ress=?, nmber=?, kalids=?, prgram=? WHERE id=?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, name);
            pst.setInt(2, age);
            pst.setString(3, gender);
            pst.setString(4, address);
            pst.setString(5, contact);
            pst.setString(6, college);
            pst.setString(7, program);
            pst.setInt(8, studentId);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data updated successfully!");

            // Update JTable
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setValueAt(name, selectedRow, 1);
            model.setValueAt(age, selectedRow, 2);
            model.setValueAt(gender, selectedRow, 3);
            model.setValueAt(address, selectedRow, 4);
            model.setValueAt(contact, selectedRow, 5);
            model.setValueAt(college, selectedRow, 6);
            model.setValueAt(program, selectedRow, 7);

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.");
            return;
        }

// Get student_id from JTable (assuming it's in column 0)
        int studentId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydata?useSSL=false", "root", "");

                String sql = "DELETE FROM dateta WHERE id=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, studentId);
                pst.executeUpdate();

                // Remove from JTable
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(null, "Record deleted successfully!");

                con.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new School().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edad;
    private javax.swing.JComboBox<String> gram;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> ledge;
    private javax.swing.JTextField nem;
    private javax.swing.JTextField num;
    // End of variables declaration//GEN-END:variables
}
